spring.application.name=LikeService

server.port = 9003
#db configuration 

spring.datasource.name=blog_app_postservice
spring.datasource.url=jdbc:mysql://localhost:3308/blog_app_postlike_service
spring.datasource.username=root
spring.datasource.password=M#kcl@1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

#Eureka Configuration For eureka client 

# Use the IP address of the machine for registration instead of hostname
eureka.instance.prefer-ip-address=true

# Tells the client to fetch the registry info from Eureka server 
# so it knows about other registered services (for service discovery)
eureka.client.fetch-registry=true

# Tells the client to register itself with the Eureka server
# so that other services can discover it
eureka.client.register-with-eureka=true

# The URL of the Eureka server where this client will register
# This is the Eureka server address, could be multiple in production
eureka.client.service-url.defaultZone=http://localhost:8761/eureka


# Kafka broker
spring.cloud.stream.kafka.binder.brokers=localhost:9092

# Consumer binding
spring.cloud.stream.bindings.likeEventConsumerMethod-in-0.destination=post-like-events
spring.cloud.stream.bindings.likeEventConsumerMethod-in-0.group=like-group
spring.cloud.stream.bindings.likeEventConsumerMethod-in-0.content-type=application/json

# Producer binding
spring.cloud.stream.bindings.like-count-out-0.destination=post-like-count-events
